### ISSUE TITLE
Malformed version number string on Heroku Postgres

### ISSUE THREAD

**Issue by swrobel** [ankane/strong_migrations#116]
I realize now that I should probably only be using this on development, but still figured I might as well raise the issue. Feel free to close if you agree.

```
vendor/ruby-2.6.5/lib/ruby/2.6.0/rubygems/version.rb:212:in `initialize': An error has occurred, this and all later migrations canceled:

Malformed version number string 11.6 (Ubuntu 11.6-1.pgdg16.04+1) (StandardError)
    from vendor/ruby-2.6.5/lib/ruby/2.6.0/rubygems/version.rb:203:in `new'
    from vendor/ruby-2.6.5/lib/ruby/2.6.0/rubygems/version.rb:203:in `new'
    from vendor/bundle/ruby/2.6.0/gems/strong_migrations-0.6.1/lib/strong_migrations/checker.rb:305:in `target_version'
    from vendor/bundle/ruby/2.6.0/gems/strong_migrations-0.6.1/lib/strong_migrations/checker.rb:268:in `postgresql_version'
    from vendor/bundle/ruby/2.6.0/gems/strong_migrations-0.6.1/lib/strong_migrations/checker.rb:83:in `perform'
    from vendor/bundle/ruby/2.6.0/gems/strong_migrations-0.6.1/lib/strong_migrations/migration.rb:9:in `method_missing'
    from db/migrate/20200202215401_add_email_opt_in_to_users.rb:3:in `change'
    from vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:828:in `exec_migration'
    from vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:812:in `block (2 levels) in migrate'
    from vendor/ruby-2.6.5/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
    from vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:811:in `block in migrate'
    from vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:473:in `with_connection'
    from vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:810:in `migrate'
    from vendor/bundle/ruby/2.6.0/gems/strong_migrations-0.6.1/lib/strong_migrations/migration.rb:5:in `migrate'
```

**Comment by ankane** [comment]
Hey @swrobel, thanks for the report! Give master a shot.
