### ISSUE TITLE
SystemStackError: stack level too deep

### ISSUE THREAD

**Issue by dup2** [ankane/strong_migrations#151]
Hi

We face the following error:
```
SystemStackError: stack level too deep
/bundle/ruby/2.6.0/gems/strong_migrations-0.7.6/lib/strong_migrations/migration.rb:11:in `method_missing'
/bundle/ruby/2.6.0/gems/strong_migrations-0.7.6/lib/strong_migrations/checker.rb:391:in `connection'
/bundle/ruby/2.6.0/gems/strong_migrations-0.7.6/lib/strong_migrations/checker.rb:408:in `postgresql?'
/bundle/ruby/2.6.0/gems/strong_migrations-0.7.6/lib/strong_migrations/checker.rb:359:in `set_timeouts'
/bundle/ruby/2.6.0/gems/strong_migrations-0.7.6/lib/strong_migrations/checker.rb:26:in `perform'
/bundle/ruby/2.6.0/gems/strong_migrations-0.7.6/lib/strong_migrations/migration.rb:11:in `method_missing'
/bundle/ruby/2.6.0/gems/strong_migrations-0.7.6/lib/strong_migrations/checker.rb:391:in `connection'
/bundle/ruby/2.6.0/gems/strong_migrations-0.7.6/lib/strong_migrations/checker.rb:408:in `postgresql?'
/bundle/ruby/2.6.0/gems/strong_migrations-0.7.6/lib/strong_migrations/checker.rb:359:in `set_timeouts'
/bundle/ruby/2.6.0/gems/strong_migrations-0.7.6/lib/strong_migrations/checker.rb:26:in `perform'
/bundle/ruby/2.6.0/gems/strong_migrations-0.7.6/lib/strong_migrations/migration.rb:11:in `method_missing'
/bundle/ruby/2.6.0/gems/strong_migrations-0.7.6/lib/strong_migrations/checker.rb:391:in `connection'
/bundle/ruby/2.6.0/gems/strong_migrations-0.7.6/lib/strong_migrations/checker.rb:408:in `postgresql?'
/bundle/ruby/2.6.0/gems/strong_migrations-0.7.6/lib/strong_migrations/checker.rb:359:in `set_timeouts'
/bundle/ruby/2.6.0/gems/strong_migrations-0.7.6/lib/strong_migrations/checker.rb:26:in `perform'
/bundle/ruby/2.6.0/gems/strong_migrations-0.7.6/lib/strong_migrations/migration.rb:11:in `method_missing'
```

We have an old migration (which should be ignored due to `StrongMigrations.start_after`) but nevertheless seems to trigger this:
(some parts removed due to internas..)

```
class AddDefaultRolesToAllUsers < ActiveRecord::Migration[5.2]
  def change
    add_column :roles, :is_admin, :boolean, default: false
    add_column :roles, :assumable, :boolean, default: false

    roles_id_map = create_default_roles!

    ActiveRecord::Base.transaction do
        connection.execute(...)
    end
  end

  private

  def create_default_roles!
    connection.execute("...")
  end

  def connection
    ActiveRecord::Base.connection
  end
end
```

The `change` method calls another method defined in the migration class and executes some raw sql.

**Comment by dup2** [comment]
Just for others to not fall into the same trap...

The problem was defining a `connection` method like above, this method is used internally by strong_migrations and triggers the error. Renaming the method helped.

**Comment by ankane** [comment]
Hey @dup2, `connection` is a method Active Record defines in migrations, so you don't want to override it. I think the infinite loop issue is due to making it private, which Strong Migrations doesn't expect.

**Comment by dup2** [comment]
> Hey @dup2, `connection` is a method Active Record defines in migrations, so you don't want to override it. I think the infinite loop issue is due to making it private, which Strong Migrations doesn't expect.

Thanks for this, this explains the loop.
