### ISSUE TITLE
Does not work with Rails 7.0.2

### ISSUE THREAD

**Issue by morgoth** [ankane/strong_migrations#171]
Rails 7.0.2 introduced versioned schema https://rubyonrails.org/2022/2/8/Rails-7-0-2-has-been-released

This new release does not work with strong_migrations.
When I want to run tests, I get:

```
rails test
rails aborted!
StrongMigrations::UnsafeMigration: 
=== Dangerous operation detected #strong_migrations ===

The force option will destroy existing tables.
If this is intended, drop the existing table first.
Otherwise, remove the force option.
my-project/db/schema.rb:18:in `block in <main>'
my-project/route-optimizer/db/schema.rb:13:in `<main>'
Tasks: TOP => db:test:load_schema
(See full trace by running task with --trace)
Migrations are pending. To resolve this issue, run:

        bin/rails db:migrate RAILS_ENV=test

You have 51 pending migrations:

20200422111512_enable_pgcrypto_extension.rb
.... all the migration files here
```

After removing strong_migrations gem, it works fine.

**Comment by ankane** [comment]
Hey @morgoth, thanks for reporting! Fixed in the commit above.

**Comment by morgoth** [comment]
@ankane Thank you. I confirm it's working. Can we have a stable release please?

**Comment by ankane** [comment]
Just pushed 0.8.0.
