### ISSUE TITLE
Non-rails ActiveRecord app

### ISSUE THREAD

**Issue by bvirlet** [ankane/strong_migrations#203]
Hello,

I'm trying to use strong_migrations for a non-rails AR app (Sinatra-based) but I'm getting the following error:

```
RACK_ENV=test bundle exec rake db:migrate
```

```
Caused by:
NoMethodError: undefined method `env' for Rails:Module

    defined?(Rails) && (Rails.env.development? || Rails.env.test?)
                             ^^^^
/Users/bruno/.gem/ruby/3.1.2/gems/strong_migrations-1.3.1/lib/strong_migrations.rb:44:in `developer_env?'
/Users/bruno/.gem/ruby/3.1.2/gems/strong_migrations-1.3.1/lib/strong_migrations/adapters/abstract_adapter.rb:52:in `target_version'
/Users/bruno/.gem/ruby/3.1.2/gems/strong_migrations-1.3.1/lib/strong_migrations/adapters/postgresql_adapter.rb:14:in `server_version'
/Users/bruno/.gem/ruby/3.1.2/gems/strong_migrations-1.3.1/lib/strong_migrations/checker.rb:123:in `check_version_supported'
/Users/bruno/.gem/ruby/3.1.2/gems/strong_migrations-1.3.1/lib/strong_migrations/checker.rb:27:in `perform'
/Users/bruno/.gem/ruby/3.1.2/gems/strong_migrations-1.3.1/lib/strong_migrations/migration.rb:16:in `block in method_missing'
/Users/bruno/.gem/ruby/3.1.2/gems/strong_migrations-1.3.1/lib/strong_migrations/migration.rb:15:in `catch'
/Users/bruno/.gem/ruby/3.1.2/gems/strong_migrations-1.3.1/lib/strong_migrations/migration.rb:15:in `method_missing'
/Users/bruno/Documents/_TheGrizzlyLabs/src/geniuscloud-api/db/migrate/20221017143856_add_conflicts_table.rb:3:in `change'
/Users/bruno/.gem/ruby/3.1.2/gems/activerecord-7.0.4/lib/active_record/migration.rb:870:in `exec_migration'
/Users/bruno/.gem/ruby/3.1.2/gems/activerecord-7.0.4/lib/active_record/migration.rb:854:in `block (2 levels) in migrate'
/Users/bruno/.gem/ruby/3.1.2/gems/activerecord-7.0.4/lib/active_record/migration.rb:853:in `block in migrate'
/Users/bruno/.gem/ruby/3.1.2/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
/Users/bruno/.gem/ruby/3.1.2/gems/activerecord-7.0.4/lib/active_record/migration.rb:852:in `migrate'
/Users/bruno/.gem/ruby/3.1.2/gems/strong_migrations-1.3.1/lib/strong_migrations/migration.rb:5:in `migrate'
/Users/bruno/.gem/ruby/3.1.2/gems/activerecord-7.0.4/lib/active_record/migration.rb:1046:in `migrate'
/Users/bruno/.gem/ruby/3.1.2/gems/activerecord-7.0.4/lib/active_record/migration.rb:1360:in `block in execute_migration_in_transaction'
/Users/bruno/.gem/ruby/3.1.2/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
/Users/bruno/.gem/ruby/3.1.2/gems/activesupport-7.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/Users/bruno/.gem/ruby/3.1.2/gems/activesupport-7.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/Users/bruno/.gem/ruby/3.1.2/gems/activesupport-7.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/Users/bruno/.gem/ruby/3.1.2/gems/activesupport-7.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/Users/bruno/.gem/ruby/3.1.2/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/Users/bruno/.gem/ruby/3.1.2/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'
/Users/bruno/.gem/ruby/3.1.2/gems/activerecord-7.0.4/lib/active_record/transactions.rb:209:in `transaction'
/Users/bruno/.gem/ruby/3.1.2/gems/activerecord-7.0.4/lib/active_record/migration.rb:1411:in `ddl_transaction'
/Users/bruno/.gem/ruby/3.1.2/gems/strong_migrations-1.3.1/lib/strong_migrations/migrator.rb:4:in `ddl_transaction'
/Users/bruno/.gem/ruby/3.1.2/gems/activerecord-7.0.4/lib/active_record/migration.rb:1359:in `execute_migration_in_transaction'
/Users/bruno/.gem/ruby/3.1.2/gems/activerecord-7.0.4/lib/active_record/migration.rb:1333:in `each'
/Users/bruno/.gem/ruby/3.1.2/gems/activerecord-7.0.4/lib/active_record/migration.rb:1333:in `migrate_without_lock'
/Users/bruno/.gem/ruby/3.1.2/gems/activerecord-7.0.4/lib/active_record/migration.rb:1282:in `block in migrate'
/Users/bruno/.gem/ruby/3.1.2/gems/activerecord-7.0.4/lib/active_record/migration.rb:1432:in `block in with_advisory_lock'
/Users/bruno/.gem/ruby/3.1.2/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
/Users/bruno/.gem/ruby/3.1.2/gems/activerecord-7.0.4/lib/active_record/migration.rb:1447:in `with_advisory_lock_connection'
/Users/bruno/.gem/ruby/3.1.2/gems/activerecord-7.0.4/lib/active_record/migration.rb:1428:in `with_advisory_lock'
/Users/bruno/.gem/ruby/3.1.2/gems/activerecord-7.0.4/lib/active_record/migration.rb:1282:in `migrate'
/Users/bruno/.gem/ruby/3.1.2/gems/activerecord-7.0.4/lib/active_record/migration.rb:1117:in `up'
/Users/bruno/.gem/ruby/3.1.2/gems/activerecord-7.0.4/lib/active_record/migration.rb:1092:in `migrate'
/Users/bruno/.gem/ruby/3.1.2/gems/activerecord-7.0.4/lib/active_record/tasks/database_tasks.rb:262:in `migrate'
/Users/bruno/.gem/ruby/3.1.2/gems/strong_migrations-1.3.1/lib/strong_migrations/database_tasks.rb:5:in `migrate'
/Users/bruno/.gem/ruby/3.1.2/gems/activerecord-7.0.4/lib/active_record/railties/databases.rake:92:in `block (2 levels) in <top (required)>'
/Users/bruno/.gem/ruby/3.1.2/bin/bundle:25:in `load'
/Users/bruno/.gem/ruby/3.1.2/bin/bundle:25:in `<main>'
Tasks: TOP => db:migrate
```

Do you know how I could work around the issue, or is this a limitation of `strong_migrations` to be strongly coupled to Rails?

Thanks!
Bruno

**Comment by ankane** [comment]
Hey @bvirlet, can you share more about how things are set up? (trying to understand why `Rails` is defined when it's not being used)

In the meantime, you can probably change `defined?(Rails)` to `defined?(Rails.env)` on that line to get it to work.

**Comment by bvirlet** [comment]
Hi @ankane. Thanks for your reply!

Rails is defined while not being used because we use `ActiveRecord` and added `rails-i18n` to have translations for the default error messages. It looks like `rails-i18n` depends on `railties` which – I think – defines `Rails`.

Here is our Gemfile.lock:
```
GIT
  remote: https://github.com/thegrizzlylabs/scout_apm_ruby
  revision: f56351352307e048b650ae46a1f97b21b6f22344
  specs:
    scout_apm (5.3.1)
      parser

GEM
  remote: https://rubygems.org/
  specs:
    ZenTest (4.11.2)
    actionmailer (7.0.4)
      actionpack (= 7.0.4)
      actionview (= 7.0.4)
      activejob (= 7.0.4)
      activesupport (= 7.0.4)
      mail (~> 2.5, >= 2.5.4)
      net-imap
      net-pop
      net-smtp
      rails-dom-testing (~> 2.0)
    actionpack (7.0.4)
      actionview (= 7.0.4)
      activesupport (= 7.0.4)
      rack (~> 2.0, >= 2.2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actionview (7.0.4)
      activesupport (= 7.0.4)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (7.0.4)
      activesupport (= 7.0.4)
      globalid (>= 0.3.6)
    activemodel (7.0.4)
      activesupport (= 7.0.4)
    activerecord (7.0.4)
      activemodel (= 7.0.4)
      activesupport (= 7.0.4)
    activesupport (7.0.4)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    addressable (2.8.1)
      public_suffix (>= 2.0.2, < 6.0)
    aggregate (0.2.3)
    andand (1.3.3)
    apnotic (1.7.0)
      connection_pool (~> 2)
      net-http2 (>= 0.18.3, < 2)
    ast (2.4.2)
    autotest (4.4.6)
      ZenTest (>= 4.4.1)
    aws-eventstream (1.2.0)
    aws-partitions (1.631.0)
    aws-sdk-core (3.149.0)
      aws-eventstream (~> 1, >= 1.0.2)
      aws-partitions (~> 1, >= 1.525.0)
      aws-sigv4 (~> 1.1)
      jmespath (~> 1, >= 1.6.1)
    aws-sdk-kms (1.58.0)
      aws-sdk-core (~> 3, >= 3.127.0)
      aws-sigv4 (~> 1.1)
    aws-sdk-s3 (1.114.0)
      aws-sdk-core (~> 3, >= 3.127.0)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.4)
    aws-sigv4 (1.5.1)
      aws-eventstream (~> 1, >= 1.0.2)
    bcrypt (3.1.16)
    benchmark-ips (2.10.0)
    better_html (2.0.1)
      actionview (>= 6.0)
      activesupport (>= 6.0)
      ast (~> 2.0)
      erubi (~> 1.4)
      parser (>= 2.4)
      smart_properties
    builder (3.2.4)
    concurrent-ruby (1.1.10)
    connection_pool (2.3.0)
    crack (0.4.3)
      safe_yaml (~> 1.0.0)
    crass (1.0.6)
    dalli (2.7.10)
    database_cleaner (1.6.1)
    dead_end (4.0.0)
    declarative (0.0.20)
    derailed (0.1.0)
      derailed_benchmarks
    derailed_benchmarks (2.1.2)
      benchmark-ips (~> 2)
      dead_end
      get_process_mem (~> 0)
      heapy (~> 0)
      memory_profiler (>= 0, < 2)
      mini_histogram (>= 0.3.0)
      rack (>= 1)
      rack-test
      rake (> 10, < 14)
      ruby-statistics (>= 2.1)
      thor (>= 0.19, < 2)
    diff-lcs (1.5.0)
    digest (3.1.0)
    domain_name (0.5.20170404)
      unf (>= 0.0.5, < 1.0.0)
    dotenv (2.2.1)
    erubi (1.11.0)
    factory_girl (4.8.0)
      activesupport (>= 3.0.0)
    fakeredis (0.7.0)
      redis (>= 3.2, < 5.0)
    faraday (1.10.2)
      faraday-em_http (~> 1.0)
      faraday-em_synchrony (~> 1.0)
      faraday-excon (~> 1.1)
      faraday-httpclient (~> 1.0)
      faraday-multipart (~> 1.0)
      faraday-net_http (~> 1.0)
      faraday-net_http_persistent (~> 1.0)
      faraday-patron (~> 1.0)
      faraday-rack (~> 1.0)
      faraday-retry (~> 1.0)
      ruby2_keywords (>= 0.0.4)
    faraday-em_http (1.0.0)
    faraday-em_synchrony (1.0.0)
    faraday-excon (1.1.0)
    faraday-httpclient (1.0.1)
    faraday-multipart (1.0.4)
      multipart-post (~> 2)
    faraday-net_http (1.0.1)
    faraday-net_http_persistent (1.2.0)
    faraday-patron (1.0.0)
    faraday-rack (1.0.0)
    faraday-retry (1.0.3)
    fcm (0.0.6)
      httparty (~> 0.10, >= 0.10.0)
    ffi (1.15.5)
    fuubar (2.2.0)
      rspec-core (~> 3.0)
      ruby-progressbar (~> 1.4)
    get_process_mem (0.2.7)
      ffi (~> 1.0)
    globalid (1.0.0)
      activesupport (>= 5.0)
    google-apis-androidpublisher_v3 (0.27.0)
      google-apis-core (>= 0.7.2, < 2.a)
    google-apis-core (0.9.0)
      addressable (~> 2.5, >= 2.5.1)
      googleauth (>= 0.16.2, < 2.a)
      httpclient (>= 2.8.1, < 3.a)
      mini_mime (~> 1.0)
      representable (~> 3.0)
      retriable (>= 2.0, < 4.a)
      rexml
      webrick
    googleauth (1.2.0)
      faraday (>= 0.17.3, < 3.a)
      jwt (>= 1.4, < 3.0)
      memoist (~> 0.16)
      multi_json (~> 1.11)
      os (>= 0.9, < 2.0)
      signet (>= 0.16, < 2.a)
    haml (5.2.2)
      temple (>= 0.8.0)
      tilt
    hashdiff (0.3.2)
    heapy (0.2.0)
      thor
    hetchy (1.0.0)
    highline (2.0.3)
    http-2 (0.11.0)
    http-cookie (1.0.3)
      domain_name (~> 0.5)
    http_accept_language (2.1.1)
    httparty (0.16.3)
      mime-types (~> 3.0)
      multi_xml (>= 0.5.2)
    httpclient (2.8.3)
    i18n (1.12.0)
      concurrent-ruby (~> 1.0)
    i18n-tasks (1.0.12)
      activesupport (>= 4.0.2)
      ast (>= 2.1.0)
      better_html (>= 1.0, < 3.0)
      erubi
      highline (>= 2.0.0)
      i18n
      parser (>= 2.2.3.0)
      rails-i18n
      rainbow (>= 2.2.2, < 4.0)
      terminal-table (>= 1.5.1)
    jmespath (1.6.1)
    json (2.6.2)
    jwt (2.5.0)
    librato-metrics (1.6.2)
      aggregate (~> 0.2.2)
      faraday (>= 0.7, < 2.0)
      multi_json
    librato-rack (1.1.1)
      hetchy (~> 1.0)
      librato-metrics (~> 1.6)
    loofah (2.19.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    memoist (0.16.2)
    memory_profiler (1.0.0)
    method_source (1.0.0)
    mime-types (3.4.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2022.0105)
    mini_histogram (0.3.1)
    mini_mime (1.1.2)
    mini_portile2 (2.8.0)
    minitest (5.16.3)
    multi_json (1.15.0)
    multi_xml (0.6.0)
    multipart-post (2.2.3)
    mustermann (2.0.2)
      ruby2_keywords (~> 0.0.1)
    net-http2 (0.18.4)
      http-2 (~> 0.11)
    net-imap (0.2.3)
      digest
      net-protocol
      strscan
    net-pop (0.1.1)
      digest
      net-protocol
      timeout
    net-protocol (0.1.3)
      timeout
    net-smtp (0.3.1)
      digest
      net-protocol
      timeout
    netrc (0.11.0)
    nio4r (2.5.8)
    nokogiri (1.13.8)
      mini_portile2 (~> 2.8.0)
      racc (~> 1.4)
    os (1.1.4)
    parallel (1.22.1)
    parser (3.1.2.1)
      ast (~> 2.4.1)
    pg (1.4.3)
    public_suffix (5.0.0)
    puma (5.6.4)
      nio4r (~> 2.0)
    racc (1.6.0)
    rack (2.2.4)
    rack-attack (6.3.0)
      rack (>= 1.0, < 3)
    rack-protection (2.2.2)
      rack
    rack-test (2.0.2)
      rack (>= 1.3)
    rack-timeout (0.4.2)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.4.3)
      loofah (~> 2.3)
    rails-i18n (7.0.5)
      i18n (>= 0.7, < 2)
      railties (>= 6.0.0, < 8)
    railties (7.0.4)
      actionpack (= 7.0.4)
      activesupport (= 7.0.4)
      method_source
      rake (>= 12.2)
      thor (~> 1.0)
      zeitwerk (~> 2.5)
    rainbow (3.1.1)
    rake (13.0.6)
    redis (4.8.0)
    regexp_parser (2.5.0)
    representable (3.2.0)
      declarative (< 0.1.0)
      trailblazer-option (>= 0.1.1, < 0.2.0)
      uber (< 0.2.0)
    rest-client (2.0.2)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 4.0)
      netrc (~> 0.8)
    retriable (3.1.2)
    rexml (3.2.5)
    rollbar (3.3.1)
    rspec (3.11.0)
      rspec-core (~> 3.11.0)
      rspec-expectations (~> 3.11.0)
      rspec-mocks (~> 3.11.0)
    rspec-core (3.11.0)
      rspec-support (~> 3.11.0)
    rspec-expectations (3.11.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.11.0)
    rspec-its (1.2.0)
      rspec-core (>= 3.0.0)
      rspec-expectations (>= 3.0.0)
    rspec-mocks (3.11.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.11.0)
    rspec-support (3.11.1)
    rubocop (1.36.0)
      json (~> 2.3)
      parallel (~> 1.10)
      parser (>= 3.1.2.1)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8, < 3.0)
      rexml (>= 3.2.5, < 4.0)
      rubocop-ast (>= 1.20.1, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 1.4.0, < 3.0)
    rubocop-ast (1.21.0)
      parser (>= 3.1.1.0)
    rubocop-rspec (2.13.1)
      rubocop (~> 1.33)
    ruby-progressbar (1.11.0)
    ruby-statistics (3.0.0)
    ruby2_keywords (0.0.5)
    rubyzip (1.3.0)
    safe_yaml (1.0.4)
    sidekiq (6.5.7)
      connection_pool (>= 2.2.5)
      rack (~> 2.0)
      redis (>= 4.5.0, < 5)
    signet (0.17.0)
      addressable (~> 2.8)
      faraday (>= 0.17.5, < 3.a)
      jwt (>= 1.5, < 3.0)
      multi_json (~> 1.10)
    sinatra (2.2.2)
      mustermann (~> 2.0)
      rack (~> 2.2)
      rack-protection (= 2.2.2)
      tilt (~> 2.0)
    sinatra-activerecord (2.0.25)
      activerecord (>= 4.1)
      sinatra (>= 1.0)
    sinatra-contrib (2.2.2)
      multi_json
      mustermann (~> 2.0)
      rack-protection (= 2.2.2)
      sinatra (= 2.2.2)
      tilt (~> 2.0)
    smart_properties (1.17.0)
    strong_migrations (1.3.1)
      activerecord (>= 5.2)
    strscan (3.0.4)
    temple (0.8.2)
    terminal-table (3.0.2)
      unicode-display_width (>= 1.1.1, < 3)
    thor (1.2.1)
    tilt (2.0.11)
    timecop (0.9.5)
    timeout (0.3.0)
    trailblazer-option (0.1.2)
    tzinfo (2.0.5)
      concurrent-ruby (~> 1.0)
    uber (0.1.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.4)
    unicode-display_width (2.3.0)
    webmock (2.3.2)
      addressable (>= 2.3.6)
      crack (>= 0.3.2)
      hashdiff
    webrick (1.7.0)
    yajl-ruby (1.4.3)
    zeitwerk (2.6.0)

PLATFORMS
  ruby

DEPENDENCIES
  actionmailer
  actionview
  activerecord
  activesupport
  andand
  apnotic
  autotest
  aws-sdk-s3
  bcrypt
  dalli
  database_cleaner
  derailed
  dotenv
  factory_girl
  fakeredis
  fcm
  fuubar
  google-apis-androidpublisher_v3
  haml
  http_accept_language
  i18n
  i18n-tasks
  librato-rack (~> 1.1)
  pg
  puma
  rack-attack
  rack-test
  rack-timeout
  rake
  redis
  rest-client
  rollbar
  rspec
  rspec-its
  rubocop
  rubocop-rspec
  rubyzip
  scout_apm!
  sidekiq
  sinatra
  sinatra-activerecord
  sinatra-contrib
  strong_migrations
  timecop
  webmock
  yajl-ruby

RUBY VERSION
   ruby 3.1.2p20

BUNDLED WITH
   2.3.7
```

**Comment by ankane** [comment]
Thanks @bvirlet! Just pushed a fix for the error, as well as added support for using `RACK_ENV` to specify the environment.

**Comment by bvirlet** [comment]
Wow :) Thanks @ankane, that was a fast response!
