### ISSUE TITLE
Rails 8.0.0.rc2 error on migrate "Wrong number of arguments"

### ISSUE THREAD

**Issue by guillaumewrobel** [ankane/strong_migrations#282]
This Rails ActiveRecord PR might have broken the migrate method used here: https://github.com/rails/rails/pull/53474/files#diff-cb5c658a1aa7877862198142775880b76b1d327ade6fd39f7c29a080535de6b7

```
ArgumentError: wrong number of arguments (given 2, expected 0..1) (ArgumentError)
/app/vendor/bundle/ruby/3.3.0/gems/activerecord-8.0.0.rc2/lib/active_record/tasks/database_tasks.rb:262:in `migrate'
/app/vendor/bundle/ruby/3.3.0/gems/strong_migrations-2.0.1/lib/strong_migrations/database_tasks.rb:5:in `migrate'
/app/vendor/bundle/ruby/3.3.0/gems/activerecord-8.0.0.rc2/lib/active_record/tasks/database_tasks.rb:255:in `block (3 levels) in migrate_all'
/app/vendor/bundle/ruby/3.3.0/gems/activerecord-8.0.0.rc2/lib/active_record/connection_adapters/abstract/connection_pool.rb:412:in `with_connection'
/app/vendor/bundle/ruby/3.3.0/gems/activerecord-8.0.0.rc2/lib/active_record/tasks/database_tasks.rb:525:in `block in with_temporary_connection'
/app/vendor/bundle/ruby/3.3.0/gems/activerecord-8.0.0.rc2/lib/active_record/tasks/database_tasks.rb:546:in `with_temporary_pool'
/app/vendor/bundle/ruby/3.3.0/gems/activerecord-8.0.0.rc2/lib/active_record/tasks/database_tasks.rb:524:in `with_temporary_connection'
/app/vendor/bundle/ruby/3.3.0/gems/activerecord-8.0.0.rc2/lib/active_record/tasks/database_tasks.rb:254:in `block (2 levels) in migrate_all'
/app/vendor/bundle/ruby/3.3.0/gems/activerecord-8.0.0.rc2/lib/active_record/tasks/database_tasks.rb:253:in `each'
/app/vendor/bundle/ruby/3.3.0/gems/activerecord-8.0.0.rc2/lib/active_record/tasks/database_tasks.rb:253:in `block in migrate_all'
/app/vendor/bundle/ruby/3.3.0/gems/activerecord-8.0.0.rc2/lib/active_record/tasks/database_tasks.rb:252:in `each'
/app/vendor/bundle/ruby/3.3.0/gems/activerecord-8.0.0.rc2/lib/active_record/tasks/database_tasks.rb:252:in `migrate_all'
```

**Comment by navidemad** [comment]
https://github.com/rails/rails/commit/ecbdfbc2127f6788c2691d4b02da87c93e0b3b9c#diff-cb5c658a1aa7877862198142775880b76b1d327ade6fd39f7c29a080535de6b7

The migration method definition has been changed recently @ankane
