### ISSUE TITLE
check constraint error with `safe_by_default`

### ISSUE THREAD

**Issue by mockdeep** [ankane/strong_migrations#286]
Strong Migrations version 2.1.0.

Based on the migration from [this other issue](https://github.com/ankane/strong_migrations/issues/285), I added a `safety_assured` block, but I'm getting an error about the check constraint.

```rb
class SetFormRequestsStepIdNotNull < ActiveRecord::Migration[7.2]
  def change
    safety_assured { change_column_null :form_requests, :step_id, false }
  end
end
```

```
$ rails db:migrate
== 20241031213510 SetFormRequestsStepIdNotNull: migrating =====================
-- validate_check_constraint(:form_requests, {:name=>"form_requests_step_id_null"})
   -> 0.0037s
-- change_column_null(:form_requests, :step_id, false)
   -> 0.0394s
bin/rails aborted!
StandardError: An error has occurred, this and all later migrations canceled: (StandardError)

Generic CHECK constraints must have a name
/home/fletch/Dropbox/projects/chalk/synchroform/db/migrate/20241031213510_set_form_requests_step_id_not_null.rb:6:in `block in change'
/home/fletch/Dropbox/projects/chalk/synchroform/db/migrate/20241031213510_set_form_requests_step_id_not_null.rb:6:in `change'

Caused by:
Generic CHECK constraints must have a name
/home/fletch/Dropbox/projects/chalk/synchroform/db/migrate/20241031213510_set_form_requests_step_id_not_null.rb:6:in `block in change'
/home/fletch/Dropbox/projects/chalk/synchroform/db/migrate/20241031213510_set_form_requests_step_id_not_null.rb:6:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

```

**Comment by ankane** [comment]
Let's discuss in #285.
