### ISSUE TITLE
undefined method 'columns' for class

### ISSUE THREAD

**Issue by chadwilken** [ankane/strong_migrations#45]
First off, I love the gem and appreciate all of your open source work.

When I run a DB migration it get the following error:

```
NameError: undefined method `columns' for class `#<Class:0x00007f9c1b3dea78>'
bin/rails:4:in `<main>'
Tasks: TOP => db:schema:dump => strong_migrations:alphabetize_columns
```

I am using makara, with the makara_postgis adapter and version 0.1.9 of strong_migrations, but also updated and tried with 0.2.2 with the same results. I have it alphabetizing the columns after a schema dump obviously and that is the part that fails. The migration "succeeds" but looks as if it fails because the schema doesn't dump.

Full backtrace
```
NameError: undefined method `columns' for class `#<Class:0x00007fd33a842320>'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/strong_migrations-0.2.2/lib/tasks/strong_migrations.rake:14:in `alias_method'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/strong_migrations-0.2.2/lib/tasks/strong_migrations.rake:14:in `singleton class'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/strong_migrations-0.2.2/lib/tasks/strong_migrations.rake:13:in `block (2 levels) in <main>'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:237:in `block in invoke_prerequisites'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:235:in `each'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:235:in `invoke_prerequisites'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:212:in `block in invoke_with_call_chain'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/railties/databases.rake:68:in `block (2 levels) in <main>'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/railties/databases.rake:61:in `block (2 levels) in <main>'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/command.rb:48:in `invoke'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<main>'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
/Users/chadwilken/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
bin/rails:4:in `<main>'
```

**Comment by ankane** [comment]
Hey @chadwilken, thanks for the report 👍 This should be fixed on master.

**Comment by chadwilken** [comment]
You’re the man, thanks.
-- 
*Chad Wilken*
1125 Aberdeen Avenue
Lincoln, NE 68512
(402) 405-7300

**Comment by chadwilken** [comment]
@ankane I hate to be the bearer of bad news, but it seems like it doesn't alphabetize the columns. It doesn't throw an error however so it's a partial win. Happy to help debug the issue, but I have limited experience with Makara's internals.

**Comment by ankane** [comment]
Are you sure you have `task "db:schema:dump": "strong_migrations:alphabetize_columns"` in your Rakefile? I tested against Makara 0.4.0 and 0.3.10.

**Comment by chadwilken** [comment]
Yea, but I am almost wondering if something is cached because if I open a rails console and run `ActiveRecord::Base.connection.columns(:users)` I get the alphabetically ordered list of columns so it definitely could be something on my end.

**Comment by ankane** [comment]
It should only alphabetize them during schema dump.

**Comment by chadwilken** [comment]
Sorry I meant to say I loaded a console, and then prepended the `StrongMigrations:: AlphabetizeColumns module to check that it was all functioning properly. If I run a migration or do a `db:schema:dump` the dump works but isn't alphabetized.

**Comment by chadwilken** [comment]
Im not sure if it matters by Im on Rails 5.2.0. Even after a full restart and uninstall older versions of the gem just to be sure, it is not alphabetizing them. It's not the end of the world, but it is a really handy feature.

**Comment by ankane** [comment]
Looks like it was specific to Rails 5.2. Should work with the latest commit.

**Comment by chadwilken** [comment]
So I still had an issue and it turned out to be PostGIS related, I opened #46 to address these issues.
